# Travis CI

sudo: required
dist: xenial
language: generic
python:
  - "2.7"
services:
  - docker
  
script:
  - cd ../../
  - git clone https://github.com/TechEmpower/FrameworkBenchmarks
  - cp -f sumeetchhetri/ffead-cpp/docker/techempower-config/* FrameworkBenchmarks/frameworks/C++/ffead-cpp
  - cp -f sumeetchhetri/ffead-cpp/web/te-benchmark-um/include/*.h FrameworkBenchmarks/frameworks/C++/ffead-cpp/te-benchmark-um/include/
  - cp -f sumeetchhetri/ffead-cpp/web/te-benchmark-um/src/*.cpp FrameworkBenchmarks/frameworks/C++/ffead-cpp/te-benchmark-um/src/
  - cd FrameworkBenchmarks && ./tfb --mode verify --test-dir C++/ffead-cpp