# Travis CI

sudo: required
dist: xenial
language: generic
python:
  - "2.7"
services:
  - docker
  
script:
  - cd ../../
  - git clone https://github.com/TechEmpower/FrameworkBenchmarks
  - cp -f sumeetchhetri/ffead-cpp/docker/techempower-config/* FrameworkBenchmarks/frameworks/C++/ffead-cpp
  - cd FrameworkBenchmarks && ./tfb --mode verify --test-dir C++/ffead-cpp