version: '3'

services:
  ffead-cpp:
    depends_on:
      - db
    image: ffead-cpp-mysql-nginx:latest
    container_name: ffead-cpp-mysql-nginx
    restart: always
    ports:
      - "8080:8080"
    networks: 
      - backend

  db:
    image: mysql-for-ffeadcpp:latest
    container_name: mysql
    ports:
      - "3306:3306"
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"