[package]
name = "thruster-ffead-cpp"
version = "0.1.0"
authors = ["Sumeet Chhetri <sumeet.chhetri@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.5"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.6.2"
thruster = "=0.9.0-alpha.11"
thruster-proc = "=0.9.0-alpha.11"
libc = "0.2.69"
bytes = "0.5.4"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
