[package]
name = "thruster_techempower"
version = "0.1.0"
authors = ["Isaac Whitfield <iw@whitfin.io>"]
edition = "2018"

[dependencies]
hyper = "0.13.5"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.6.2"
thruster = "=0.9.0-alpha.11"
thruster-proc = "=0.9.0-alpha.11"
libc = "0.2.69"
bytes = "0.5.4"

[profile.release]
codegen-units = 1
opt-level = 3
