[package]
name = "rocket-ffead-cpp"
version = "0.1.0"
authors = ["Sumeet Chhetri <sumeet.chhetri@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.69"
futures = "0.3.1"
rocket = "0.4.5"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
