name: Build ffead-cpp base docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the ffead-cpp-4.0 base docker image
      run: |
        git clone https://github.com/TechEmpower/FrameworkBenchmarks
        cp -f docker/DockerFile-tfb-test FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp.dockerfile
        cp -f docker//techempower-config/benchmark_config.json FrameworkBenchmarks/frameworks/C++/ffead-cpp/ 
        cd FrameworkBenchmarks
        ./tfb --mode verify --test ffead-cpp
