name: Build docker image for ffead-cpp with seastar backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image for ffead-cpp with seastar backend
      run: |
        cd lang-server-backends/c++/seastar
        docker build --file seastar-http.dockerfile .
